services:
  - type: web
    name: oil-sif-predict
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
